name: Test

on:
  pull_request:
    paths:
      - 'app/**'

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: |
      !(startsWith(github.head_ref, 'dev-') && github.base_ref == 'develop') &&
      !(github.head_ref == 'develop' && github.base_ref == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        working-directory: app
        run: go mod download

      - name: Run unit tests
        working-directory: app
        run: |
          go test -v ./src/cmd/...
          go test -v ./src/config/...
          go test -v ./src/core/...
          go test -v ./src/infra/...
          go test -v ./src/utils/...

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    if: |
      !(startsWith(github.head_ref, 'dev-') && github.base_ref == 'develop') &&
      !(github.head_ref == 'develop' && github.base_ref == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        working-directory: app
        run: go mod download

      - name: Run E2E tests
        working-directory: app
        run: go test -v ./src/e2e/...
